export const styles = {
  MainBox: {
    color: "white",
    height: { xs: "100vh", sm: "100vh" },
    display: "flex",
    backgroundImage: "url(../assets/mainBG.png)",
    backgroundPosition: "center",
    backgroundSize: "cover",
    justifyContent: "center",
  },
  progressBox: {
    backgroundColor: "#34241c",
    height: "15px",
    padding: "2px 3px",
    display: "flex",
    alignItems: "center",
    borderRadius: "5px",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#f59226",
    color: "#f59226",
    textAlign: "center",
    transition: "width 0.1s ease-in-out",
    borderRadius: "2px",
  },
  popupBox: {
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1000,
    transform: "translate(-50%, -50%)",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: "black",
  },
  rewardPopUp: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "75%", sm: "65%", md: "50%" },
    bgcolor: "#1c1411",
    boxShadow: 24,
    padding: "24px",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    alignItem: "center",
    textAlign: "center",
    borderRadius: "10px",
    border: ".5px solid #d39f42",
    zIndex: 2000,
  },
  ButtonBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  Button: {
    background: "linear-gradient(to bottom, #fff, #f09340, #e76414)",
    color: "black",
    textTransform: "none",
    padding: "5px 25px",
    width: { xs: "100%", sm: "25%", md: "20%" },
    margin: "20px 0px",
  },
  text: {
    textAlign: "center",
    fontSize: "16px",
    color: "#35241C",
    fontWeight: 700,
  },
  textColor: {
    textAlign: "center",
    fontSize: "12px",
    color: "#DCC794",
  },
  closeIcon: {
    display: "flex",
    justifyContent: "flex-end",
  },
  rewardsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    width: "100%",
  },
  rewardLabel: {
    fontWeight: "bold",
    color: "#444",
  },
  rewardButton: {
    background: "linear-gradient(to bottom, #fff, #f09340, #e76414)",
    color: "black",
    textTransform: "none",
    padding: "5px 25px",
    width: { xs: "100%", sm: "30%" },
    margin: "20px 0px",
  },
  rewardCloseIcon: {
    color: "white",
    border: ".5px solid",
    borderRadius: "5px",
  },
  mainImageBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    margin: { xs: "50px 0px 20px", md: "50px 0px" },
  },
  levelupImage: { height: { xs: "60px", md: "100px" }, width: "100%" },
  levelbadgeImage: {
    height: { xs: "185px", md: "250px", lg: "190px" },
    width: "100%",
  },
  levelTitle: { color: "#291911", marginTop: "20px" },
  rewardHeading: {
    fontSize: { xs: "29px", sm: "44px", md: "44px" },
    fontWeight: 900,
    color: "#F3BA2F",
  },
  rewardTitle: {
    color: "#F3BA2F",
    fontSize: { xs: "18px", md: "22px", lg: "26px" },
  },
  rewardText: { color: "#C8AA7A", marginTop: "25px" },
  rewardIconBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  rewardIcons: { height: 80, width: 200 },
  rewardIconsText: { color: "white", margin: "0px 10px" },
  rewardImageBox: { display: "flex", justifyContent: "center" },
  rewardImages: { height: 80, width: 80, margin: "0px 2px" },
  animationBox: {
    width: {xs:"100%",lg:"60%"},
    height: { xs: "200px", sm: "500px", md: "600px", lg: "60%" },
  },
};
